# Generated by Django 5.2.8 on 2025-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/uploads/'),
        ),
    ]
